all:
  hosts:
    node1:
      ansible_host: 192.168.56.10
      ip: 192.168.56.10
      access_ip: 192.168.56.10
    node2:
      ansible_host: 192.168.56.11
      ip: 192.168.56.11
      access_ip: 192.168.56.11
    node3:
      ansible_host: 192.168.56.12
      ip: 192.168.56.12
      access_ip: 192.168.56.12
    node4:
      ansible_host: 192.168.56.13
      ip: 192.168.56.13
      access_ip: 192.168.56.13
    node5:
      ansible_host: 192.168.56.14
      ip: 192.168.56.14
      access_ip: 192.168.56.14
  children:
    kube_control_plane:
      hosts:
        node1:
        node2:
        node3:
    kube_node:
      hosts:
        node1:
        node2:
        node3:
        node4:
        node5:
    etcd:
      hosts:
        node1:
        node2:
        node3:
    calico_rr:
      hosts: {}
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node: